### ISSUE TITLE
Inflating error

### ISSUE THREAD

**Issue by maxim-petroshenko** [egslava/edittext-mask#9]
Hello,
When I try to run my app I see the error Binary XML file line #50. Error inflating class br.com.sapereaude.maskedEditText.MaskedEditText
and in preview i have this:
The following classes could not be instantiated:
- br.com.sapereaude.maskedEditText.MaskedEditText (Open Class, Show Exception, Clear Cache)

I have the line in build.gradle 
compile 'ru.egslava:MaskedEditText:1.0.5'
so there have to be no problem, but unfortunately we have...

Using Android Studio

**Comment by egslava** [comment]
Hi and welcome! :-)
Can you share a source code that reproduces the problem? :-)

**Comment by egslava** [comment]
No problems :-(

![edittext-mask-demo 2017-04-05 18-27-55](https://cloud.githubusercontent.com/assets/1143228/24703481/9f446c98-1a2d-11e7-86a3-03a04a77693f.png)

**Comment by maxim-petroshenko** [comment]
So here is a layout

<?xml version="1.0" encoding="utf-8"?>

<LinearLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:mask="http://schemas.android.com/apk/res-auto"
    android:orientation="vertical"
    android:layout_width="match_parent"
    android:layout_height="wrap_content">


    <LinearLayout

        android:id="@+id/title_block_linear_layout"
        xmlns:android="http://schemas.android.com/apk/res/android"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:orientation="horizontal"
        android:gravity="center_vertical">

        <TextView
            android:id="@+id/title"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:text="@string/form.amount.write.off"
            android:textSize="17sp"
            android:layout_marginTop="5dp"
            android:textColor="@color/product.list.text.color"
            android:layout_marginBottom="8dp"
            android:layout_marginLeft="15dp"/>

        <ImageButton
            android:id="@+id/information"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:background="@android:color/white"
            android:src="@drawable/ic_info"
            android:visibility="gone"
            android:layout_marginLeft="4dp"
            android:layout_marginTop="-2dp"
            />

    </LinearLayout>

    <View
        android:layout_width="match_parent"
        android:layout_height="1px"
        android:layout_marginTop="4dp"
        android:background="@color/formdivider"/>

    <LinearLayout
        android:id="@+id/money.bloc.linear.layout"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:gravity="center"
        android:orientation="horizontal">

        <br.com.sapereaude.maskedEditText.MaskedEditText
            android:id="@+id/edittext_block_edit_text_amount"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            />


    </LinearLayout>
    <LinearLayout
        android:layout_width="match_parent"
        android:orientation="vertical"
        android:layout_marginTop="-17dp"
        android:layout_height="wrap_content">
        <View
            android:layout_width="match_parent"

            android:layout_height="1px"
            android:background="@color/formdivider"/>
        <View
            android:layout_width="match_parent"

            android:layout_height="17dp"
            android:background="@color/white"/>
    </LinearLayout>
</LinearLayout>

**Comment by maxim-petroshenko** [comment]
That is how we are using it in code

package com.ufc.OFK.utils;

/**
 * Copyright (C) Created by Vlad Kolomysov on 17.10.16.
 * All rights reserved. United Financial Capital Bank, Moscow
 */

import android.content.Context;
import android.text.Editable;
import android.text.TextWatcher;
import android.view.LayoutInflater;
import android.view.View;
import android.widget.AdapterView;
import android.widget.CheckBox;
import android.widget.CompoundButton;
import android.widget.Spinner;

import com.ufc.OFK.R;
import com.ufc.OFK.data.models.Form.EditText.FormFieldEditText;
import com.ufc.OFK.data.models.Form.Flag.FormFieldFlag;
import com.ufc.OFK.data.models.Form.Form;
import com.ufc.OFK.data.models.Form.Money.FormFieldMoney;
import com.ufc.OFK.data.models.Form.Money.Money;
import com.ufc.OFK.data.models.Form.ProductList.FormFieldProductList;
import com.ufc.OFK.data.models.Form.ProductList.FormFieldValue;
import com.ufc.OFK.data.models.Form.StringList.FormFieldStringList;
import com.ufc.OFK.ui.adapters.slidemenu.left.GetFormProductListAdapter;
import com.ufc.OFK.ui.adapters.slidemenu.left.MoneyAdapter;
import com.ufc.OFK.utils.createForm.EditTextBlock;
import com.ufc.OFK.utils.createForm.FactoryMethodFormBlock;
import com.ufc.OFK.utils.createForm.FlagBlock;
import com.ufc.OFK.utils.createForm.ICreateBlockOfForm;
import com.ufc.OFK.utils.createForm.MoneyBlock;
import com.ufc.OFK.utils.createForm.ProductListBlock;
import com.ufc.OFK.utils.createForm.StringListBlock;
import com.ufc.OFK.utils.createForm.TextBlock;
import com.fasterxml.jackson.databind.ObjectMapper;

import com.google.gson.Gson;

import java.io.IOException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;


import br.com.sapereaude.maskedEditText.MaskedEditText;
import rx.subjects.PublishSubject;


import android.text.InputType;


import static android.media.CamcorderProfile.get;
import static rx.Observable.combineLatest;


/**
 * Copyright (C) Created by Vlad Kolomysov on 30.05.16.
 * All rights reserved. United Financial Capital Bank, Moscow
 */

// CreateDynamicFormIT1  for creating dynamic Form
public class CreateDynamicFormET0 {

    private ArrayList<View> mArrayOfChild = new ArrayList<>();

    private View mChild;

    private Form mForm;
    private Context mContext;

    private FormFieldProductList sCbaProductList;

    private FormFieldEditText sCbaEditText;
    private FormFieldStringList sCbaStringList;
    private FormFieldFlag sCbaFlag;
    private FormFieldMoney sCbaMoney;

    public static final String TAG = "dynamic";

    // Money block
    private Money mMoney1;
    private FormFieldStringList mStringList;
    private Money mMoney2 = new Money();
    private ObjectMapper mMapper = new ObjectMapper();

    // номер блока fiels в форме
    private Integer mNumberOfFormBlock = 0;

    private Map<Integer, String> mIFormIdMap = new HashMap<Integer, String>();

    //// здесь храню массив объектов с общим интерфейсом
    private FactoryMethodFormBlock factoryMethodFormBlock = new FactoryMethodFormBlock();
    ICreateBlockOfForm mICreateBlockOfForm;
    private ArrayList<ICreateBlockOfForm> mIArrayOfBlockForm = new ArrayList<>();
    ////////

    ////
    private Map<String, Integer> mArrayIdFields = new HashMap<>();
    private List<String> mArrayVar = new ArrayList<>();

    PublishSubject<CharSequence> money1210 = PublishSubject.create();
    PublishSubject<CharSequence> text1240 = PublishSubject.create();

    //здесь храним две валюты
    private Map<Integer, String> mMapForCurrency = new HashMap<>();
    private ArrayList<Integer> mArrayCurrency = new ArrayList<>();

    //
    Integer mIndxInFieldsKurs = 0;
    Integer mIndxFormulaKurs = 0;


    Integer mIdOfMaskedEditText = 0;
    Boolean mIdOfMaskedEditTextFirstValue = false;

    // конструктор
    public CreateDynamicFormET0(Form form, Context context, int k) {
        this.mForm = form;
        this.mContext = context;
        mNumberOfFormBlock = k;
    }

    //
    private FormFieldValue mProductListValue = new FormFieldValue();

    // создаем форму
    public ArrayList<View> createDynamicForm(){



        LayoutInflater inflater = (LayoutInflater) mContext.getSystemService( Context.LAYOUT_INFLATER_SERVICE );

        String nameOfFormField;

        for (int i = 0; i < mNumberOfFormBlock; i++)
        {

            if (mForm.fields.get(i).hidden)
            {
                mIArrayOfBlockForm.add(i,null);
                continue;
            }

            nameOfFormField = mForm.fields.get(i).type;

            // распоковываем пришедшие данные формы и рисуем форму
            if (nameOfFormField.toLowerCase().equals("ProductList".toLowerCase()))
            {

                mIFormIdMap.put(i,mForm.fields.get(i).id);

               /* Logger.log(Constants.TAG,"i = "+i+", type = "+nameOfFormField);

                mICreateBlockOfForm = factoryMethodFormBlock.chooseFormOfBlock("ProductList");
                ProductListBlock productListBlock = (ProductListBlock) mICreateBlockOfForm;
                mIArrayOfBlockForm.add(productListBlock);
                mChild = mICreateBlockOfForm.createBlock(inflater,mContext,mForm,i);

                productListBlock.mMaterialSpinnerProductList.setAdapter(new GetFormProductListAdapter(mContext,mForm,i));

                Logger.log("currency"," title = "+mForm.fields.get(i).title);
                productListBlock.mTextFormBlock.setText(mForm.fields.get(i).title);

                // в словарь засунули две валюты RUB
                mMapForCurrency.put(i,"RUB");
                mArrayCurrency.add(i);

                if (mForm.fields.get(i).readOnly){
                    productListBlock.mMaterialSpinnerProductList.setEnabled(false);
                    productListBlock.mMaterialSpinnerProductList.setClickable(false);
                    productListBlock.mScrollView.setBackgroundResource(R.color.product_list_not_editable);
                }

                // если value значение не равно нулю
                if (!mForm.fields.get(i).getFormFieldProductList().getValue().isEmpty()){

                    try {
                        FormFieldValue mProductListValue = mMapper.readValue(mForm.fields.get(i).getFormFieldProductList().value, FormFieldValue.class);
                        String productNumber = mProductListValue.getProductNumber();

                        // ищем в массиве номер с таким id
                        for (int k = 0; k < mForm.fields.get(i).getFormFieldProductList().values.size(); k++){
                            String str = mForm.fields.get(i).getFormFieldProductList().values.get(k);
                            if (str.toLowerCase().contains(productNumber.toLowerCase())){
                                productListBlock.mMaterialSpinnerProductList.setSelection(k);
                            }
                        }

                    } catch (IOException e) {
                        e.printStackTrace();
                    }

                }

                // если связей нет
                if (mForm.fields.get(i).idLink.isEmpty()){
                    observeSelectMaterialSpinnerProductList(productListBlock.mMaterialSpinnerProductList,i,false,"",-1,-1);
                }
                else {
                    observeSelectMaterialSpinnerProductList((Spinner) mChild.findViewById(R.id.spinner_product_list),i,true,mForm.fields.get(i).idLink,-1,-1);
                }*/


                //// FIXME: 21.03.17 - осталось со старой формы ETO
               /* /////// ********************************************

                FormFieldValue formFieldValue = new FormFieldValue();

                String find;
                String goal;

                try {
                    formFieldValue = mMapper.readValue(((FormFieldProductList) mForm.fields.get(i)).value, FormFieldValue.class);
                } catch (IOException e) {
                    e.printStackTrace();
                }
                find = formFieldValue.getProductID();


                int size = ((FormFieldProductList) mForm.fields.get(i)).values.size();


                for (int k = 0; k < size; k++){

                    try {
                        formFieldValue = mMapper.readValue(((FormFieldProductList) mForm.fields.get(i)).values.get(k), FormFieldValue.class);
                    } catch (IOException e) {
                        e.printStackTrace();
                    }
                    goal = formFieldValue.getProductID();


                    if (find.contains(goal)){

                        Logger.log("findKKKK","findKKKK find k = "+k);
                        productListBlock.mMaterialSpinnerProductList.setSelection(k);

                    }

                }
                /////// *********************************************/

                Logger.log(Constants.TAG,"i = "+i+", type = "+nameOfFormField);

                mICreateBlockOfForm = factoryMethodFormBlock.chooseFormOfBlock("ProductList");
                ProductListBlock productListBlock = (ProductListBlock) mICreateBlockOfForm;
                mIArrayOfBlockForm.add(productListBlock);
                mChild = mICreateBlockOfForm.createBlock(inflater,mContext,mForm,i);

                productListBlock.mMaterialSpinnerProductList.setAdapter(new GetFormProductListAdapter(mContext,mForm,i));
                productListBlock.mTextFormBlock.setText(mForm.fields.get(i).title);


                ///// получить валюту и засунуть в словарь
                try {
                    mProductListValue = mMapper.readValue(mForm.fields.get(i).getFormFieldProductList().value, FormFieldValue.class);
                    // в словарь засунули две валюты RUB
                    mMapForCurrency.put(i,mProductListValue.productCurrency);
                    // в массив добавили валюты
                    mArrayCurrency.add(i);
                }
                catch (Exception e){

                }
                ///////////

                if (mForm.fields.get(i).readOnly){
                    productListBlock.mMaterialSpinnerProductList.setEnabled(false);
                    productListBlock.mMaterialSpinnerProductList.setClickable(false);
                    productListBlock.mScrollView.setBackgroundResource(R.color.product_list_not_editable);
                }

                // если value значение не равно нулю

                if (!mForm.fields.get(i).getFormFieldProductList().getValue().isEmpty()){

                    try {
                        mProductListValue = mMapper.readValue(mForm.fields.get(i).getFormFieldProductList().value, FormFieldValue.class);
                        String productNumber = mProductListValue.getProductNumber();

                        // ищем в массиве номер с таким id
                        for (int k = 0; k < mForm.fields.get(i).getFormFieldProductList().values.size(); k++){
                            String str = mForm.fields.get(i).getFormFieldProductList().values.get(k);
                            if (str.toLowerCase().contains(productNumber.toLowerCase())){
                                productListBlock.mMaterialSpinnerProductList.setSelection(k);
                            }
                        }

                    } catch (IOException e) {
                        e.printStackTrace();
                    }

                }

                // если связей нет
                if (mForm.fields.get(i).idLink.isEmpty()){
                    observeSelectMaterialSpinnerProductList(productListBlock.mMaterialSpinnerProductList,i,false,"",-1,-1);
                }
                else {
                    observeSelectMaterialSpinnerProductList((Spinner) mChild.findViewById(R.id.spinner_product_list),i,true,mForm.fields.get(i).idLink,-1,-1);
                }


                mArrayOfChild.add(mChild);
            }
            else if (nameOfFormField.toLowerCase().equals("Money".toLowerCase()))
            {
                Logger.log(Constants.TAG,"i = "+i+", type = "+nameOfFormField);

                mIFormIdMap.put(i,mForm.fields.get(i).id);

                mICreateBlockOfForm = factoryMethodFormBlock.chooseFormOfBlock("Money");
                MoneyBlock moneyBlock = (MoneyBlock) mICreateBlockOfForm;
                mIArrayOfBlockForm.add(moneyBlock);
                mChild = mICreateBlockOfForm.createBlock(inflater,mContext,mForm,i);

                // if readOnly = true - editText might be written
                if (mForm.fields.get(i).readOnly){
                    moneyBlock.mEditTextAmountWriteOf.setEnabled(false);

                    moneyBlock.mLinearLayout.setBackgroundResource(R.color.product_list_not_editable);
                    moneyBlock.mMaterialSpinnerMoneyCurrency.setBackgroundResource(android.R.color.transparent);
                }



                try {
                    mMoney1 = mMapper.readValue(mForm.fields.get(i).getFormMoney().value, Money.class);
                } catch (IOException e) {
                    e.printStackTrace();
                }

                // если нет связей
                if (mForm.fields.get(i).idLink.isEmpty() && mMoney1.amount.isEmpty())
                {
                    moneyBlock.mMaterialSpinnerMoneyCurrency.setAdapter(new MoneyAdapter(mContext, mForm.fields.get(i).getFormMoney().values));
                    observeSelectMaterialSpinnerMoney1(moneyBlock.mMaterialSpinnerMoneyCurrency,i);
                }
                else
                {
                    // есть связь = idLink isn't empty
                    ArrayList<String> currency = new ArrayList<>();
                    try {

                        mMoney2.setAmount(mMoney1.amount);
                        mMoney2.setCurrency(mMoney1.currency);

                        //// FIXME: 15.09.16 - если валюта одна - то берем из выбранного источника
                        //mMoney2.setCurrency("");
                        ////
                        currency.add(mMoney2.getCurrency());
                        //mMoney2 = null;
                    }
                    catch (Exception e)
                    {
                        //  Logger.log(Constants.TAG, "listMaterialSpinner (Exception e) = " + e.toString());
                    }

                    moneyBlock.mMaterialSpinnerMoneyCurrency.setEnabled(false);
                    moneyBlock.mMaterialSpinnerMoneyCurrency.setClickable(false);

                    moneyBlock.mEditTextAmountWriteOf.setText(mMoney2.getAmount());

                    moneyBlock.mMaterialSpinnerMoneyCurrency.setAdapter(new MoneyAdapter(mContext,currency));

                    observeSelectMaterialSpinnerMoney1(moneyBlock.mMaterialSpinnerMoneyCurrency,i);

                }
                observeSelectEditTextForMoney(((MaskedEditText) mChild.findViewById(R.id.edittext_block_money_amount)),i);
                mArrayOfChild.add(mChild);
            }
            else if (nameOfFormField.toLowerCase().equals("Flag".toLowerCase()))
            {
                Logger.log(Constants.TAG,"i = "+i+", type = "+nameOfFormField);

                mIFormIdMap.put(i,mForm.fields.get(i).id);

                mICreateBlockOfForm = factoryMethodFormBlock.chooseFormOfBlock("Flag");
                FlagBlock flagBlock = (FlagBlock) mICreateBlockOfForm;
                mIArrayOfBlockForm.add(flagBlock);
                mChild = mICreateBlockOfForm.createBlock(inflater,mContext,mForm,i);

                observeSelectFlag(flagBlock.mCheckBox,i);

                mArrayOfChild.add(mChild);
            }
            else if (nameOfFormField.toLowerCase().equals("StringList".toLowerCase()))
            {
                Logger.log(Constants.TAG,"i = "+i+", type = "+nameOfFormField);

                mIFormIdMap.put(i,mForm.fields.get(i).id);

                mICreateBlockOfForm = factoryMethodFormBlock.chooseFormOfBlock("StringList");
                StringListBlock stringListBlock = (StringListBlock) mICreateBlockOfForm;
                mIArrayOfBlockForm.add(stringListBlock);
                mChild = mICreateBlockOfForm.createBlock(inflater,mContext,mForm,i);


                /*try
                {
                    mStringList = mMapper.readValue(mForm.fields.get(i).getFormStringList().values, FormFieldStringList.class);
                }
                catch (IOException e)
                {
                    e.printStackTrace();
                }

                // есть связь = idLink isn't empty
                ArrayList<String> currency = new ArrayList<>();
                try {

                    mMoney2.setAmount(mMoney1.amount);
                    mMoney2.setCurrency(mMoney1.currency);

                    //// FIXME: 15.09.16 - если валюта одна - то берем из выбранного источника
                    //mMoney2.setCurrency("");
                    ////
                    currency.add(mMoney2.getCurrency());
                    //mMoney2 = null;
                }
                catch (Exception e)
                {
                    //  Logger.log(Constants.TAG, "listMaterialSpinner (Exception e) = " + e.toString());
                }*/

                stringListBlock.mMaterialSpinnerStringList.setAdapter(new MoneyAdapter(mContext,mForm.fields.get(i).getFormStringList().values));

                observeSelectMaterialSpinnerStringList((Spinner) mChild.findViewById(R.id.spinner_string_list),i);

                mArrayOfChild.add(mChild);

            }
            else if (nameOfFormField.toLowerCase().equals("Text".toLowerCase()))
            {

                mIFormIdMap.put(i,mForm.fields.get(i).id);

                Logger.log(Constants.TAG,"i = "+i+", type = "+nameOfFormField);

                mICreateBlockOfForm = factoryMethodFormBlock.chooseFormOfBlock("Text");
                TextBlock textBlock = (TextBlock) mICreateBlockOfForm;
                mIArrayOfBlockForm.add(textBlock);
                mChild = mICreateBlockOfForm.createBlock(inflater,mContext,mForm,i);

                textBlock.mTextFormBlock.setText(mForm.fields.get(i).title);

                Logger.log("textblock","mForm.fields.get(i).title = "+mForm.fields.get(i).title);

                if (mForm.fields.get(i).title.toLowerCase().contains("По курсу".toLowerCase())){
                    mChild.setVisibility(View.GONE);
                }



                if (!mForm.fields.get(i).title.isEmpty()){
                    mArrayOfChild.add(mChild);
                }

            }
            else if (nameOfFormField.toLowerCase().equals("EditText".toLowerCase()))
            {

                mIFormIdMap.put(i,mForm.fields.get(i).id);

                Logger.log(Constants.TAG,"i = "+i+", type = "+nameOfFormField);

                mICreateBlockOfForm = factoryMethodFormBlock.chooseFormOfBlock("edit");
                EditTextBlock editTextBlock = (EditTextBlock) mICreateBlockOfForm;
                mIArrayOfBlockForm.add(editTextBlock);

                mChild = mICreateBlockOfForm.createBlock(inflater,mContext,mForm,i);

                if (!mForm.fields.get(i).mask.isEmpty() && mForm.fields.get(i).getFormFieldEditText().getValue().isEmpty()){

                    mIdOfMaskedEditText = i;

                    mIdOfMaskedEditTextFirstValue = false;

                    String mask = mForm.fields.get(i).mask;
                    mask = mask.replaceAll("#", "9");

                    Logger.log("getForm","trans 1 = "+mask);


                    editTextBlock.mEditTextAmountWriteOf.setMask(mask);
                    editTextBlock.mEditTextAmountWriteOf.setInputType(InputType.TYPE_CLASS_NUMBER);
                    char c = '_';
                    editTextBlock.mEditTextAmountWriteOf.setHint(c);

                }
                else if (!mForm.fields.get(i).mask.isEmpty() && !mForm.fields.get(i).getFormFieldEditText().getValue().isEmpty()){

                    mIdOfMaskedEditText = i;

                    mIdOfMaskedEditTextFirstValue = true;

                    String mask = mForm.fields.get(i).mask;
                    mask = mask.replaceAll("#", "9");

                    Logger.log("getForm","getFrom 2"+mask);

                    editTextBlock.mEditTextAmountWriteOf.setMask(mask);
                    editTextBlock.mEditTextAmountWriteOf.setInputType(InputType.TYPE_CLASS_NUMBER);
                    char c = '_';
                    editTextBlock.mEditTextAmountWriteOf.setHint(c);

                    editTextBlock.mEditTextAmountWriteOf.setText(mForm.fields.get(i).getFormFieldEditText().value);
                }
                else {
                    Logger.log("getFrom","getFrom mask nothing");
                }

                // if readOnly = true - editText might be written
                if (mForm.fields.get(i).readOnly){
                    editTextBlock.mEditTextAmountWriteOf.setEnabled(false);
                    editTextBlock.mLinearLayout.setBackgroundResource(R.color.product_list_not_editable);
                    editTextBlock.mEditTextAmountWriteOf.setText(((FormFieldEditText) mForm.fields.get(i)).value);
                    editTextBlock.mLinearLayout.setBackgroundResource(R.color.product_list_not_editable);
                }

                // set unique id for edittext
                editTextBlock.mEditTextAmountWriteOf.setId(i*100+i);

                observeSelectEditText(editTextBlock.mEditTextAmountWriteOf,i);
                mArrayOfChild.add(mChild);

            }

        }


        return mArrayOfChild;
    }


    //следим за MaterialSpinner типа Money
    public void observeSelectMaterialSpinnerMoney1(Spinner MaterialSpinner, final Integer integer) {


        MaterialSpinner.setOnItemSelectedListener(new AdapterView.OnItemSelectedListener() {
            @Override
            public void onItemSelected(AdapterView<?> parent, View view, int position, long id) {
                // смотрим что выбрали
                String item = (String) parent.getItemAtPosition(position);
                // заменяем в форме
                sCbaMoney = (FormFieldMoney) mForm.getElement(integer);
                try {
                    mMoney1 = mMapper.readValue(mForm.fields.get(integer).getFormMoney().value, Money.class);
                    mMoney1.setCurrency(item);

                    String jsonInString = mMapper.writeValueAsString(mMoney1);
                    sCbaMoney.setValue(jsonInString);
                    mForm.replace(integer,sCbaMoney);
                }
                catch (Exception e){

                }
            }
            @Override
            public void onNothingSelected(AdapterView<?> parent) {

            }
        });
    }


    // следим за MaterialSpinner типа StringList
    public void observeSelectMaterialSpinnerStringList(Spinner MaterialSpinner, final Integer integer) {
        MaterialSpinner.setOnItemSelectedListener(new AdapterView.OnItemSelectedListener() {
            @Override
            public void onItemSelected(AdapterView<?> parent, View view, int position, long id) {

                String item = (String) parent.getItemAtPosition(position);

                Logger.log("stringlist","stringlist = "+item);

                if (item.toLowerCase().contains("счет") && !mIdOfMaskedEditTextFirstValue){

                    ((EditTextBlock) mIArrayOfBlockForm.get(mIdOfMaskedEditText)).mEditTextAmountWriteOf.setText("");

                    ((EditTextBlock) mIArrayOfBlockForm.get(mIdOfMaskedEditText)).mEditTextAmountWriteOf.setMask("99999.999.9.99999999999");
                    ((EditTextBlock) mIArrayOfBlockForm.get(mIdOfMaskedEditText)).mEditTextAmountWriteOf.setInputType(InputType.TYPE_CLASS_NUMBER);
                    char c = '_';
                    ((EditTextBlock) mIArrayOfBlockForm.get(mIdOfMaskedEditText)).mEditTextAmountWriteOf.setHint(c);

                }
                else if(item.toLowerCase().contains("карта") && !mIdOfMaskedEditTextFirstValue){

                    Logger.log("edittext","mIdOfMaskedEditText = "+mIdOfMaskedEditText);

                    ((EditTextBlock) mIArrayOfBlockForm.get(mIdOfMaskedEditText)).mEditTextAmountWriteOf.setText("");

                    ((EditTextBlock) mIArrayOfBlockForm.get(mIdOfMaskedEditText)).mEditTextAmountWriteOf.setMask("9999.9999.9999.9999");
                    ((EditTextBlock) mIArrayOfBlockForm.get(mIdOfMaskedEditText)).mEditTextAmountWriteOf.setInputType(InputType.TYPE_CLASS_NUMBER);
                    char c = '_';
                    ((EditTextBlock) mIArrayOfBlockForm.get(mIdOfMaskedEditText)).mEditTextAmountWriteOf.setHint(c);

                }

                mIdOfMaskedEditTextFirstValue = false;

                sCbaStringList = (FormFieldStringList) mForm.getElement(integer);
                sCbaStringList.setValue(item);
                mForm.replace(integer,sCbaStringList);
            }
            @Override
            public void onNothingSelected(AdapterView<?> parent) {

            }
        });
    }

    // следим за EditText типа Money
    private void observeSelectEditTextForMoney(MaskedEditText editText, final Integer integer)
    {
        editText.addTextChangedListener(new TextWatcher() {
            @Override
            public void beforeTextChanged(CharSequence s, int start, int count, int after) {

            }

            @Override
            public void onTextChanged(CharSequence s, int start, int before, int count) {
            }

            @Override
            public void afterTextChanged(Editable s) {
                // смотрим что ввели в EditText
                String item = (String) s.toString();
                // заменили в форме
                sCbaMoney = (FormFieldMoney) mForm.getElement(integer);


                try {
                    mMoney1 = mMapper.readValue(mForm.fields.get(integer).getFormMoney().value, Money.class);
                    mMoney1.setAmount(item);

                    String jsonInString = mMapper.writeValueAsString(mMoney1);
                    sCbaMoney.setValue(jsonInString);
                    mForm.replace(integer,sCbaMoney);

                }
                catch (Exception e){

                }
                mForm.replace(integer,sCbaMoney);
            }
        });
    }


    // следим за EditText типа EditText
    private void observeSelectEditText(MaskedEditText editText, final Integer integer) {

        editText.addTextChangedListener(new TextWatcher() {
            @Override
            public void beforeTextChanged(CharSequence s, int start, int count, int after) {

            }

            @Override
            public void onTextChanged(CharSequence s, int start, int before, int count) {

            }

            @Override
            public void afterTextChanged(Editable s) {

                Logger.log("getForm","trans = "+s.toString());

                String item = s.toString();

                if (!mForm.fields.get(integer).mask.isEmpty()){
                    item = editText.getText().toString();
                }
                else {
                    item = s.toString();
                }

                sCbaEditText = (FormFieldEditText) mForm.getElement(integer);
                sCbaEditText.setValue(item);
                mForm.replace(integer,sCbaEditText);
            }
        });
    }

    // следим за CheckBox типа Flag
    public void observeSelectFlag(CheckBox checkBox, final Integer integer) {

        checkBox.setOnCheckedChangeListener(new CompoundButton.OnCheckedChangeListener() {
            @Override
            public void onCheckedChanged(CompoundButton buttonView, boolean isChecked) {
                sCbaFlag = (FormFieldFlag) mForm.getElement(integer);
                sCbaFlag.setValue(isChecked);
                mForm.replace(integer,sCbaFlag);

            }
        });
    }


    // следим за MaterialSpinner типа ProductList
    private void observeSelectMaterialSpinnerProductList(Spinner materialSpinner, final Integer integer, Boolean isLink, String idLink, Integer indxInFields, Integer indxFormula)
    {

        Logger.log("getProductCurrency","ProductList, зашел в поле integer= "+integer);

        materialSpinner.setOnItemSelectedListener(new AdapterView.OnItemSelectedListener() {
            @Override
            public void onItemSelected(AdapterView<?> parent, View view, int position, long id) {

                // засовываем в форму
                FormFieldValue item = (FormFieldValue) parent.getItemAtPosition(position);

                //mCurrency1 = item.getProductCurrency();

                Gson gson = new Gson();
                String jsonRepresentation = gson.toJson(item);
                sCbaProductList = (FormFieldProductList) mForm.getElement(integer);
                sCbaProductList.setValue(jsonRepresentation);
                //sCbaProductList.setValue(item);
                mForm.replace(integer,sCbaProductList);

                if (mMapForCurrency.containsKey(integer)){
                    mMapForCurrency.put(integer,item.getProductCurrency());
                }
                // есть ли связь
                Logger.log("getForm"," isLink =  "+idLink+", mIArrayOfBlockForm ="+mIArrayOfBlockForm+", item.getProductCurrency() = "+item.getProductCurrency()+", mIFormIdMap = "+mIFormIdMap);
                Logger.log("getForm"," getKeyByMap(mIFormIdMap,idLink)) = "+getKeyByMap(mIFormIdMap,idLink));
                Logger.log("getForm"," isLink = "+isLink);
                if (isLink){
                    // здесь меняется значение spinner у MoneyBlock
                    // делаем новый массив с валютами
                    ArrayList currency = new ArrayList<String>();
                    currency.add(item.getProductCurrency());

                    // с тем спиннер, которая есть связь, вставляем новую валюту
                    ((MoneyBlock) mIArrayOfBlockForm.get(getKeyByMap(mIFormIdMap,idLink))).mMaterialSpinnerMoneyCurrency.setAdapter(new MoneyAdapter(mContext,currency));
                }



            }
            @Override
            public void onNothingSelected(AdapterView<?> parent) {

            }
        });
    }



    // определяем курс валют
    public Double pairOfCurrency(Integer numberBlockOfFormula){

        String pairOfCurrencyString ="";

        for (int hhh = 0; hhh < mArrayCurrency.size(); hhh++){

            pairOfCurrencyString = pairOfCurrencyString+mMapForCurrency.get(mArrayCurrency.get(hhh))+"_";

        }


        pairOfCurrencyString = pairOfCurrencyString.substring(0, pairOfCurrencyString.length()-1);



        for (int k = 0; k < mForm.formula.get(numberBlockOfFormula).parameters.size(); k++){

            if (pairOfCurrencyString.toLowerCase().contains(mForm.formula.get(numberBlockOfFormula).parameters.get(k).parName.toLowerCase())){
                return Double.parseDouble(mForm.formula.get(numberBlockOfFormula).parameters.get(k).parValue);
            }

        }

        if (pairOfCurrencyString.toLowerCase().contains("RUB_RUB".toLowerCase())){

            return 1d;
        }
        else if (pairOfCurrencyString.toLowerCase().contains("USD_USD".toLowerCase())){
            return 1d;
        }
        else if (pairOfCurrencyString.toLowerCase().contains("EUR_EUR".toLowerCase())){
            return 1d;
        }
        else {
            return 1d;
        }
    }



    // get key by value in Map, например, id = 1250 => 4 - номер в массиве.
    private Integer getKeyByMap(Map<Integer,String> hashMap, String value){
        for (Map.Entry<Integer, String> e : hashMap.entrySet()) {
            if (e.getValue().toLowerCase().equals(value)) {
                return e.getKey();
            }
        }
        return null;
    }

    // what's an element: MoneyBlock, ProductListBlock etc
    public String whatIsTheBlock(Integer indxInFields){
        if (mIArrayOfBlockForm.get(indxInFields) instanceof ProductListBlock)
        {
            return "ProductListBlock";
        }
        else if (mIArrayOfBlockForm.get(indxInFields) instanceof MoneyBlock)
        {
            return "MoneyBlock";
        }
        else if (mIArrayOfBlockForm.get(indxInFields) instanceof FlagBlock)
        {
            return "FlagBlock";
        }
        else if (mIArrayOfBlockForm.get(indxInFields) instanceof StringListBlock)
        {
            return "StringListBlock";
        }
        // сюда КУРС
        else if (mIArrayOfBlockForm.get(indxInFields) instanceof TextBlock)
        {
            return "TextBlock";
        }
        else if (mIArrayOfBlockForm.get(indxInFields) instanceof EditTextBlock)
        {
            return "EditTextBlock";
        }
        return "";
    }
}

**Comment by egslava** [comment]
Hi, @maxim-petroshenko 
Everything is ok :-) You need to point the mask as well :-) You can find the complete example in README.md, here's your example code:

```xml
        <br.com.sapereaude.maskedEditText.MaskedEditText
            android:id="@+id/edittext_block_edit_text_amount"
            app:allowed_chars="1234567890"
            app:mask="+7(###)###-##-##"
            app:keep_hint="true"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            />

```

**Comment by egslava** [comment]
Sorry, forgot to ask you: has your problem resolved now? You can use any mask in the beginning - you can change it in runtime, but, of course, for Preview you need just anything so you have to specify it explicitly.

**Comment by maxim-petroshenko** [comment]
This mistake is gone now
The following classes could not be instantiated:
- br.com.sapereaude.maskedEditText.MaskedEditText (Open Class, Show Exception, Clear Cache)
And now in preview everything is OK

But i still have this
Binary XML file line #50. Error inflating class br.com.sapereaude.maskedEditText.MaskedEditText

**Comment by egslava** [comment]
Wow, ok, the first part is solved, that nice :-) if you don't mind - could you create another issue with the detailed description (what's the line that throws the exception?) I'll close this one and refer on it issue when somebody will have the same error.

**Comment by maxim-petroshenko** [comment]
Wow! Sorry! You were right!. The thing is that I was using this EditText twice, and did not add 
app:allowed_chars="1234567890"
app:mask="+7(###)###-##-##"
app:keep_hint="true"
to the second EditText.
Thank you very much for such quick responce and help!
